### ISSUE TITLE
11. width for text smaller 50% 

### ISSUE THREAD

**Issue by freethlua** [freethlua/individualogist-whats-your-archetype#10]
>11. Please make width for text smaller, maybe around 50% of screen. That should be perfect.

**Comment by freethlua** [comment]
Fixed? 
![image](https://user-images.githubusercontent.com/8020662/27709419-a7592dac-5d39-11e7-9e22-1c1de5c2cf15.png)

**Comment by zhixinlin** [comment]
Well, kind of. I'm guessing you used font size vh or em so the text resizes to the container. But more on this later. 

We're in the process of re-doing the transcripts to make the sentences shorter. This was an oversight on my part and I do apologise if this makes things harder for you. 

I'm guessing that with shorter sentences, the font size will refit itself to appear larger since it won't take up as much space within the container. So you won't have to do anything about this for now.

Please wait for our update on the new transcriptions later today (will be ready in a couple hours or so). We'll see how it looks with the new transcripts and make the sizing adjustments from there. 

This applies to the love compatibility image as well, no action has to be taken for that either until the new transcripts are up and running. Thanks Freeth!

**Comment by zhixinlin** [comment]
[6](https://user-images.githubusercontent.com/29788050/27760156-290a2f88-5e73-11e7-98e3-8e8439adc1cc.png)

Hi freeth, please refer to above attached screenshot. Please change text font size to 2em, and center text for love compatibility in mobile devices.

On a separate note, we'd like to include a little header below the logo that states "Testname's Archetype Reading". About font size 2em as well, "Testname" in bold. Please refer to below screenshot.

![free-archetype](https://user-images.githubusercontent.com/19595715/27760216-9bb9704c-5e74-11e7-968f-f705c855fc59.png)

I'm not sure how troublesome it will be to add that. Let me know if you encounter any troubles with it.

**Comment by zhixinlin** [comment]
Hi Freeth, 

Just an update to the above, please change the font size for the text slider to 2.5em instead, and keep the Name's Archetype Reading at 2em. Thanks!

**Comment by freethlua** [comment]
Updated. 

I've added the header. But where should it appear when compatibility image is up? Let me know. 

It's now responsive and gets automatically vertically centered or inline based on width and device-ratio
[![](https://thumbs.gfycat.com/TatteredUnripeGharial-size_restricted.gif)](https://gfycat.com/TatteredUnripeGharial)


||| 
|---|---| 
|On rather small screens:| I've set it to 1-1.5em:| 
| ![image](https://user-images.githubusercontent.com/8020662/27794241-f5d34502-601e-11e7-8436-62fdf631b056.png)      | ![image](https://user-images.githubusercontent.com/8020662/27794260-07913c54-601f-11e7-80d1-d68e44a82c52.png)
