### ISSUE TITLE
URGENT: Personalization Tag aweber-field="name" + "email" not working

### ISSUE THREAD

**Issue by zhixinlin** [freethlua/individualogist-whats-your-archetype#53]
Hi Freeth,

Just encountered an issue with our written sales pages, where the aweber-field tags are not parsing the names. All of them are displaying the text within the tags, e.g. "Friend", "you@email.com", instead of parsing the actual names retrieved from the form.

archetype.individualogist.com seems to be working fine, it's just the <span aweber-field="name"> and <span aweber-field="email"> tags that seem to be broken. 

Not sure what caused the issue, but I checked this yesterday and there wasn't much of a problem. Could you please assist us with this? Personalisation is crucial to our conversions, and I'd greatly appreciate it if you could prioritize fixing this issue over everything else. Thanks, Freeth!

**Comment by freethlua** [comment]
Hi there. I didn't quite understand, could you please elaborate more on this? 

What does "written sales pages" refer to here? What are tags, e.g. "Friend", "you@email.com"? I haven't hard-coded any such defaults (friend, you@email) in the app itself.

**Comment by zhixinlin** [comment]
Hi Freeth,

Thanks for responding.

This was done months back. We had an issue with wanting to display customer names and e-mails on our pages that were retrieved from the Aweber form in the quiz results optin page. You helped us solve this with your javascript magic by using the following tags:

<span aweber-field="name">Name</span> (in our case, we switched with "friend" in case visitors land the page without filling in the form)
<span aweber-field="email">Email</span> (switched with "you@email.com" in case visitors land on the page without filling in the form again)

If you refer to the following links, you'll see that the span tags used are no longer displaying the names retrieved from the aweber form, and are only displaying the default values specified between the span tags:

http://individualogist.com/diminishing-your-shadow-reading-car/
http://individualogist.com/deluxe-archetype-report-ruler-reading-3/

Let me know if you have any memory of this. Thanks, Freeth!

**Comment by zhixinlin** [comment]
`<span aweber-field="name">Name</span> (in our case, we switched with "friend" in case visitors land the page without filling in the form)
'<span aweber-field="email">Email</span> (switched with "you@email.com" in case visitors land on the page without filling in the form again)`

Oops, forget to add the code insertion thingy

**Comment by zhixinlin** [comment]
Hi Freeth,

Looking to get this fixed asap, our ads are still running and I'd appreciate it if you could look into it for us :) Do keep me updated and if you have trouble understanding what the problem is!

**Comment by freethlua** [comment]
<details>
<summary>
Fixed. 
</summary>

Earlier, when the quiz was being taken on the `individualogist.com` domain, the fields (name/email) were saved in `localStorage` (user's browser cache) which doesn't works across subdomains. So now since the quiz is separated into its own subdomain `archetype.individualogist.com` the fields from this are no longer accessible on `individualogist.com`. 

To fix this I'm now redirecting all outbound traffic from `archetype.individualogist.com` to `individualogist.com` by attaching a query string with relevant info, like `individualogist.com/.../?name=xxx&email=yyy`. A new script on `individualogist.com` then saves these fields from the URL. Then the old script can consume those fields and do it's job.
</details>
