### ISSUE TITLE
Refactor for separating slider components and deluxe/regular slider

### ISSUE THREAD

**Issue by freethlua** [freethlua/individualogist-whats-your-archetype#56]
Just finished up with a [major refactor](https://bitbucket.org/aaronlfreeth/whats-your-archetype/commits/all?search=separation) separating the slider and related components. 

The main slider is separated into `/reading` and `/deluxe` (with `/deluxe?follow-up` that replaces `/reading?deluxe=follow-up` - please update the URLs in your mailler, but for now also they're automatically redirected))

All the slider-related components are now kept separate as [src/components/slider-image-XXX](../tree/staging/src/components) and any number of them can be added. Earlier `love-compatibility` was the same as `display-image` causing troubles in managing it's special case css (header on bottom). With this all images are treated components which may be simple images or complex pieces, such as the globe required in #25

Please go through the entire app (from `?new`) to make sure no discrepancies have been introduced.

**Comment by zhixinlin** [comment]
Hi Freeth,

Thank you for this. Everything looks great with a couple of mobile optimization issues which should be easy enough to fix with by establishing image widths, please see the screenshots below:

![screen shot 2017-08-14 at 12 35 38 pm](https://user-images.githubusercontent.com/19595715/29258736-aae5e0b8-80ee-11e7-91e2-61c629d329ec.png)
![screen shot 2017-08-14 at 12 37 37 pm](https://user-images.githubusercontent.com/19595715/29258737-aae6bc04-80ee-11e7-91b1-f74348367fd7.png)
![screen shot 2017-08-14 at 12 42 03 pm](https://user-images.githubusercontent.com/19595715/29258738-ab00c644-80ee-11e7-8c87-570a827b89aa.png)

Do note that the issue is present in all slider images.

Another 2 minor issues lie within the exit-pop (when user attempts to close a window and receives a prompt).

1. User redirected to a dead link:
http://archetype.individualogist.com/deluxe-archetype-report-hero-reading-3/?name=zx&email=linzedex@gmail.com

It should redirect to:
http://individualogist.com/deluxe-archetype-report-hero-reading-3/?name=zx&email=linzedex@gmail.com

2. User receives 2 prompts when attempting to exit. If possible, would it be possible to remove the first prompt which says "Do you want to leave this site?" and have it replaced with the one that says "CLAIM YOUR $10 DISCOUNT NOW". If this can be done, please edit the text in the latter to say "Wait! Your Individuation Journey Has Merely Just Begun. Click On The OK Button To Proceed!". But if it's not possible to remove the first prompt, then please remove the second prompt entirely.

![screen shot 2017-08-14 at 12 42 36 pm](https://user-images.githubusercontent.com/19595715/29258801-40818fb4-80ef-11e7-8a39-f13f7b85740b.png)
![screen shot 2017-08-14 at 12 50 50 pm](https://user-images.githubusercontent.com/19595715/29258802-408d836e-80ef-11e7-83bc-9a6f60009a34.png)

Thanks Freeth!

**Comment by freethlua** [comment]
Fixed:

Images in the slider are set to `max-width: 80%; max-height: 80%`

Exit popup:

1. Exit popup will redirect correctly in the master. On staging it tried to change the domain name from `staging.archetype.individualogist.com` to `archetype.individualogist.com` (i.e. removes the topmost subdomain), so it'll work correctly on master when changing domain name from `archetype.individualogist.com`  to `individualogist.com` 

2. Exit popup now only displays the 1 popup, the first one. It was not possible to customize the message on the 1st popup or to display the 2nd popup without the 1st one.

**Comment by zhixinlin** [comment]
I see, thanks for getting back to me on this, shouldn't be an issue then. Mobile optimisation issues seem to be fine now as well. Thanks for fixing this!
