### ISSUE TITLE
Toast popup at top-right

### ISSUE THREAD

**Issue by freethlua** [freethlua/individualogist-whats-your-archetype#57]
Added a little toast popup on top-right showing keyboard shortcuts.

Disappears after 3s, reappears on hover.

![image](https://user-images.githubusercontent.com/8020662/29248547-493e9d3e-8038-11e7-9fe6-93c538abf1ee.png)

**Comment by zhixinlin** [comment]
Hi Freeth,

In light of how the seekTo function isn't working, I also noticed that using the arrow keys to seek forwards/backwards causes syncing issues, slider-image display issues, and issues with the engagement-based pop-up feature.

It's nothing major, and we can do without having it fixed and simply keep these shortcuts for our own convenience rather than the convenience of users. I guess the best solution would be to hide the toast display for the time-being.

Please assist with hiding/removing it. After which, we can migrate all changes to the master folder. Thanks, Freeth!

**Comment by freethlua** [comment]
removed
