### ISSUE TITLE
Upload New Questions To Staging and Master

### ISSUE THREAD

**Issue by zhixinlin** [freethlua/individualogist-whats-your-archetype#59]
Hi Freeth,

Please assist with uploading a new set of quiz questions. You can upload it to both staging and master along with the new changes in the other issues. Please also help me look through the file to ensure that formatting and everything is correct - wouldn't want anything to go wrong. 

Thanks Freeth :)

[questions.js.zip](https://github.com/freethlua/individualogist-whats-your-archetype/files/1225005/questions.js.zip)

**Comment by freethlua** [comment]
Added. Fixed a small typo, otherwise it was all good. 

File is in `src/data/questions.js` ([staging](../tree/staging/src/data/questions.js) (new), [master](../tree/master/src/data/questions.js) (old))

http://staging.archetype.individualogist.com?new

Have only added it in staging since hopefully we can bring master up-to-date to staging now (instead of adding it the two branches separately).

**Comment by zhixinlin** [comment]
Terrific, thanks for the swift action!
